name: Terraform Plan

on:
  push:
    branches:
      - feature/initial_infra

  pull_request:
    branches:
      - feature/initial_infra

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Environment/Preprod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ 6d7b26b7-69fb-4507-aa80-ca7f6a291a2e }}
          tenant-id: ${{ 4484e5b8-c184-4c3c-8f23-4b3cb0236e76 }}
          subscription-id: ${{ 00435966-ecad-4915-abba-fb27e9d97e04 }}

      - name: Check Azure Login
        run: az account show

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false