name: Terraform Plan

on:
  push:
    branches:
      - feature/initial_infra

  pull_request:
    branches:
      - feature/initial_infra

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Environment/Preprod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: 5cb9ef1a-b147-469b-891a-3e22d411dcd7
          tenant-id: 6fe55cd5-23f3-4d17-b1ba-ed059ca96c26
          subscription-id: d69ba375-ddb4-4f23-9b02-2d4aa0f4f7e

      - name: Check Azure Login
        run: az account show

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false